export const WORKER_PERMISSION_CATALOG = [
  'category:get',
  'category:create',
  'category:update',
  'category:delete',
  'comment:get',
  'comment:create',
  'comment:update',
  'comment:delete',
  'dashboard:get',
  'discount:get',
  'discount:create',
  'discount:update',
  'discount:delete',
  'message:get',
  'message:create',
  'message:update',
  'message:delete',
  'order:get',
  'order:create',
  'order:update',
  'order:delete',
  'product:get',
  'product:create',
  'product:update',
  'product:delete',
  'reaction:get',
  'reaction:create',
  'reaction:delete',
  'slider:get',
  'slider:create',
  'slider:update',
  'slider:delete',
  'stock:get',
  'stock:update',
  'user:show',
  'user:block',
  'vacancy:get',
  'vacancy:create',
  'vacancy:update',
  'vacancy:delete',
  'vacancy:rate',
  'warehouse:get',
  'warehouse:create',
  'warehouse:update',
  'warehouse:delete',
  'warehouse:income',
  'warehouse:expense',
  'worker:get',
  'worker:create',
  'worker:update',
  'worker:delete',
] as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  warehouse: [
    'product:get',
    'product:update',
    'stock:get',
    'stock:update',
    'warehouse:get',
    'warehouse:income',
    'warehouse:expense',
    'order:get',
  ],
  seller: ['product:get', 'order:create', 'order:get', 'order:update'],
  manager: [
    'dashboard:get',
    'category:get',
    'category:create',
    'category:update',
    'category:delete',
    'product:get',
    'product:create',
    'product:update',
    'product:delete',
    'order:get',
    'order:update',
    'warehouse:get',
    'vacancy:get',
    'vacancy:create',
    'vacancy:update',
    'vacancy:delete',
    'slider:get',
    'slider:create',
    'slider:update',
    'slider:delete',
  ],
  admin: [...WORKER_PERMISSION_CATALOG],
};

export const WORKER_ROLES = Object.keys(ROLE_PERMISSIONS);
export const VALID_WORKER_PERMISSIONS: string[] = [
  ...WORKER_PERMISSION_CATALOG,
];
