'use client'

import React, { useState, useEffect } from 'react'
import { View, Text, ScrollView, StyleSheet, Dimensions, Pressable, TouchableOpacity, TextInput, Platform } from 'react-native'
import { uselocationStorage } from 'app/store/useLocationStore';
import { useLanStorage } from 'app/store/useLanStore'

const Location = ({ setLocationOpen }: { setLocationOpen: (open: boolean) => void }) => {
    const lan = useLanStorage(state => state.lan)
    const setLocation = uselocationStorage(state => state.setLocation);
    const [searchValue, setSearchValue] = useState('')
    const uzbekistanLocations: string[] = [
        "Abdukarim",
        "Ahmad Yassaviy",
        "Alaja",
        "Alamli",
        "Altinko'l (Qo'ng'irot tumani)",
        "Andijon",
        "Angor",
        "Angren",
        "Anhorli",
        "Arabon",
        "Arabxona (Jaloir)",
        "Arbabalar",
        "Arsif",
        "Asaka",
        "Asqar",
        "Avliyoota",
        "Avval",
        "Ayvalik",
        "Azizobod",
        "Babalakota",
        "Baland Gardiyon",
        "Baliqchi",
        "Balta",
        "Bandixon",
        "Bardanko'l",
        "Batosh",
        "Baxt",
        "Baynalmilal",
        "Bekat",
        "Bekobod",
        "Bekobod (Bog'dod tumani)",
        "Bereshum",
        "Beruni",
        "Beruniy (Qiyichirchiq tumani)",
        "Beshariq",
        "Beshbuloq",
        "Beshkapa",
        "Beshkent",
        "Beshrabod",
        "Beshtuva",
        "Birlik",
        "Bo'jay",
        "Bo'ka",
        "Bo'lish",
        "Bo'rbaliq",
        "Bo'ston",
        "Bo'ston (Ellikqali tumani)",
        "Bo'ston (Oltinsoy tumani)",
        "Bo'ston (Zarbdor tumani)",
        "Bog'dod",
        "Bog'iturkon",
        "Bog'izag'on",
        "Bog'ot",
        "Bog'zor",
        "Bogdan",
        "Boyovut",
        "Boysun",
        "Buloqboshi",
        "Bulung'ur",
        "Bunyodkor",
        "Buramatut",
        "Burchmullo",
        "Buston (Bo'ka tumani)",
        "Buvayda",
        "Buxoro",
        "Chandir",
        "Changi",
        "Chanoq",
        "Charxin",
        "Chekshura",
        "Chelak",
        "Chibintepa",
        "Chimboy",
        "Chimyon",
        "Chinabod",
        "Chinoz",
        "Chirchiq",
        "Chiroqchi",
        "Cho'rindi",
        "Chodak",
        "Chorbog'",
        "Chorraha",
        "Chorshanbe",
        "Chortoq",
        "Chortoq (Guliston tumani)",
        "Chorvoq",
        "Chorvoqguzar",
        "Choydori",
        "Chulkuvar",
        "Chust",
        "Chuuya",
        "Chuvalachi",
        "Chuvama",
        "Dahbed",
        "Dalig'uzor",
        "Dalvarzin (Andijon viloyati)",
        "Dalvarzin (Toshkent viloyati)",
        "Dangir",
        "Dangʻara",
        "Dardoq",
        "Dasht",
        "Dashtobod",
        "Deggaron",
        "Dehoji",
        "Dehqonobod",
        "Dehqonobod (Qashqadaryo viloyati)",
        "Denov",
        "Denov (Shafirqon tumani)",
        "Dilkushod",
        "Do'ngqishloq",
        "Do'rmon",
        "Do'rmon (Karmana tumani)",
        "Do'stlarobod",
        "Do'stlik",
        "Do'stlik (Denov tumani)",
        "Do'stlik (Do'stlik tumani)",
        "Do'stlik (Guliston tumani)",
        "Do'stlik (Uzun tumani)",
        "Do'stobod",
        "Dusimbiy",
        "Egizbuloq",
        "Erkin",
        "Erkin (Sariosiyo tumani)",
        "Eshmatoul",
        "Eshonguzor",
        "Etimshak",
        "Fargʻona",
        "Farxod",
        "Fayziobod",
        "Fayziobod (Asaka tumani)",
        "Forish",
        "Furqat",
        "G'alaba",
        "G'allaorol",
        "G'o's",
        "G'oliblar",
        "G'oybu",
        "G'uzor",
        "Gagarin",
        "Galaosiya",
        "Galaquduq",
        "Gazgan",
        "Geofizika",
        "Gijduvon",
        "Gul",
        "Gulbahor",
        "Gulbog",
        "Guliston",
        "Guliston (Qibray tumani)",
        "Guliston (Yuqorichirchiq tumani)",
        "Guliston (Zangiota tumani)",
        "Gullanbog'",
        "Gulobod",
        "Gulobod (Surxondaryo viloyati)",
        "Gulzar",
        "Gulzar (Paxtakor tumani)",
        "Gurlan",
        "Gurumsaroy",
        "Guvalak",
        "Gʻazalkent",
        "Gʻishtkoʻprik",
        "Hamzaobod",
        "Hasanboy",
        "Hayit",
        "Hayotobod",
        "Hisorak",
        "Hulkar",
        "Humson",
        "Iftixor",
        "Iftixor (Muzrabot tumani)",
        "Ijant",
        "Indavak",
        "Ingichka",
        "Ishtixon",
        "Iskavot",
        "Ispanza",
        "Istiqlol",
        "Ittifoq",
        "Izboskan",
        "Jag'albaïly",
        "Jalaquduq",
        "Jambul",
        "Jangaboy",
        "Janubiy Olamishik",
        "Jaqtiliq",
        "Jarqo'rg'on",
        "Jartepa",
        "Jayraxona",
        "Jeynov",
        "Jilva",
        "Jiydakapa",
        "Jizzax",
        "Jizzaxlik",
        "Jo'ynav",
        "Jomboy",
        "Jondor",
        "Juma",
        "Jumabazar (Bekobod tumani)",
        "Jumabazar (Olot tumani)",
        "Jumabazar (Yuqori Chirchiq tumani)",
        "Jumashuy",
        "Jurek",
        "Juren",
        "Kakaydi",
        "Kalkonota (Navbaxor tumani)",
        "Kandigon",
        "Kangli",
        "Kangli (Jomboy tumani)",
        "Kangli (Shovot tumani)",
        "Kanimex",
        "Kaptarxona",
        "Karamaz",
        "Kara Oy",
        "Karkidan",
        "Karmana",
        "Karvon (Arabsaroy)",
        "Kattaqo'rg'on",
        "Katta Ramadon",
        "Kavola Mahmud",
        "Kegayli",
        "Kelauchi",
        "Keles",
        "Kildan",
        "Kimyogarlar",
        "Kitob",
        "Ko'hna Kalon",
        "Ko'kcha",
        "Ko'kdala",
        "Ko'kterak",
        "Ko'k-Terak",
        "Kogon",
        "Kosari",
        "Koson",
        "Kosonsoy",
        "Koʻhna Shoʻrcha",
        "Koʻksaroy",
        "Krasnogorsk",
        "Kuliyan",
        "Kulob",
        "Kulonxona",
        "Kumarik",
        "Kuprik Bashi",
        "Kuyganyor",
        "Kuyun",
        "Labiro'd",
        "Lagan",
        "Lagandi",
        "Lalmiqor",
        "Lolazor",
        "Loyish",
        "Madaniyat",
        "Mahallai-Mirishkor",
        "Malikrabot",
        "Mallaboy",
        "Manak",
        "Mang'it",
        "Margʻilon",
        "Marhamat",
        "Marjonbuloq",
        "Markaz",
        "Mash'al",
        "Mashak",
        "Maymanoq",
        "Mindon",
        "Mindonobod",
        "Mingchinor",
        "Mirbozor",
        "Mirmiron",
        "Miroqi",
        "Misr",
        "Mitan",
        "Mo'ynoq",
        "Muborak",
        "Mug'lon",
        "Mulkanlik",
        "Mulloyon",
        "Muratali",
        "Muruntov",
        "Mustaqillik",
        "Mustaqillik (Chiroqchi tumani)",
        "Mustaqillik (Pskent tumani)",
        "Namangan",
        "Namdanak",
        "Namuna",
        "Namuna (To‘rtko‘l tumani)",
        "Nanay",
        "Narpay (Karmana tumani)",
        "Navbahor",
        "Navbahor (Namangan tumai)",
        "Navoiiy",
        "Navoiy",
        "Navro'z",
        "Navro'z (Yuqorichirchiq tumani)",
        "Nazarbek",
        "Niyozbash",
        "Niyozbotir",
        "Norinkapa",
        "Novaboshi",
        "Novkent",
        "Novmetan",
        "Nukus",
        "Nurafshon",
        "Nurbuloq",
        "Nuriston",
        "Nurobod",
        "Nurobod (Ohangaron tumani)",
        "Nurota",
        "O'rmonbek",
        "O'fta Oqchi",
        "O'rtaovul",
        "O'rtasaroy",
        "O'rtayap",
        "O'zbekiston",
        "O'zbekiston (Qashqadaryo viloyati)",
        "Odil",
        "Ohangaron",
        "Olimbek",
        "Olimkent",
        "Olmaliq",
        "Olmazor (Chinoz tumani)",
        "Olmos",
        "Olot",
        "Oltiariq",
        "Oltinariq",
        "Oltinko'l",
        "Oqmang'it",
        "Oqoltin",
        "Oqqovoq",
        "Oqqoʻrgʻon",
        "Oqtosh",
        "Otchopar",
        "Oxunboboev",
        "Oyim",
        "Ozod Vatan (Muzrobod tumani)",
        "O‘rtaqishloq",
        "Pang",
        "Parchanxas",
        "Pargos",
        "Parkent",
        "Paxta (Chinoz tumani)",
        "Paxtachi",
        "Paxtachi (Beruniy tumani)",
        "Paxtakor",
        "Paxtaobod",
        "Paxtaobod (Sardoba tumani)",
        "Paxtazor",
        "Paxtazor (Toshkent viloyati)",
        "Payariq",
        "Payshanba",
        "Pishagar",
        "Piskent",
        "Pitnak",
        "Pop",
        "Poshxurt",
        "Povulgon",
        "Poytug'",
        "Po‘latdarxon",
        "Qahramon",
        "Qamashi",
        "Qanliko'l",
        "Qaqir",
        "Qaravul",
        "Qarshi",
        "Qashqari",
        "Qatartol",
        "Qat-Qal'a",
        "Qayqi",
        "Qibray",
        "Qilichinok",
        "Qipchaq",
        "Qirarik",
        "Qiyot",
        "Qizilariq",
        "Qizilqo'rg'on",
        "Qizil Shalola",
        "Qiziltepa",
        "Qo`shtegirmon",
        "Qo'g'ali",
        "Qo'g'ay",
        "Qo'ng'irot",
        "Qo'qonboy",
        "Qo'qoni",
        "Qo'rg'oncha",
        "Qo'rg'oncha (Namangan tumani)",
        "Qo'rg'ontepa",
        "Qo'shariq",
        "Qo'shkupir",
        "Qo'shqo'rg'on",
        "Qo'shrobod",
        "Qo'shtepa",
        "Qodirist",
        "Qoraboy",
        "Qorabug'",
        "Qorako'l",
        "Qoranko'l",
        "Qorao'zak",
        "Qoraqo'yli",
        "Qoraqushchi",
        "Qoraqushxona",
        "Qorashina",
        "Qorashiq",
        "Qorasuv",
        "Qorasuv (Qo'rg'ontepa tumani)",
        "Qorato'be",
        "Qora Xitoy",
        "Qorayantoq",
        "Qorovulbozor",
        "Qosh Yog'och",
        "Qozonkekten",
        "Qoʻqon",
        "Qo‘shtepa (Andijon viloyati)",
        "Quduqcha",
        "Qumariqobod",
        "Qumqo'rg'on",
        "Qunduzyak",
        "Qurama (Andijon tumani)",
        "Qurama (Oltinsoy tumani)",
        "Qurbonov",
        "Quva",
        "Quvasoy",
        "Quyaboshi",
        "Rapqon",
        "Ravot (Samarqand viloyati)",
        "Rishton",
        "Romitan",
        "Rovot",
        "Sabzikor",
        "Salar",
        "Samarqand",
        "Samarqandquduq",
        "Sanam",
        "Sang",
        "Sarbozor",
        "Sardoba",
        "Sariasiya",
        "Sarik (Qiziriq tumani)",
        "Sari Qangli",
        "Saritepa",
        "Sasbaka",
        "Sayrob Chinor",
        "Sayxun",
        "Shahand",
        "Shahrisabz",
        "Shahrixon",
        "Shamaton",
        "Shampan",
        "Shamsiobod (Toshkent tumani)",
        "Sharg'un",
        "Shergiron",
        "Sherobod",
        "Sherobod (Qo'shko'pir tumani)",
        "Shirin",
        "Shix",
        "Shiхmashhad",
        "Sho'ralisoy",
        "Sho'rchi",
        "Sho'rchi (Guliston MFY)",
        "Shodlik",
        "Shodlik (Oqoltin tumani)",
        "Shofirkon",
        "Shohidonlar",
        "Shorko'l",
        "Shovot",
        "Shoyimbek",
        "Shumanay",
        "Sijjak",
        "Sirdaryo",
        "So'fon",
        "So'lti",
        "Sohibkor (Xovos tumani)",
        "Sohil",
        "Soyliq",
        "Sukok",
        "Sulton Segizboyev",
        "Sutkibuloq",
        "Talimarjon",
        "Talkok",
        "Talloshqon",
        "Tamabahrin",
        "Tarnov",
        "Taskent",
        "Tavois",
        "Taxiatosh",
        "Taxtako'pir",
        "Temirkovuk",
        "Temirxo`ja",
        "Tepakurgon",
        "Teraktagi",
        "Terakzor",
        "Tergachi",
        "Termiz",
        "Timiryazev",
        "Tinchlik",
        "Tinchlik (Beruniy tumani)",
        "To'qboy",
        "To'rtayg'ir",
        "To'rtko'l",
        "Toshbuloq",
        "Toshkent",
        "Toshloq",
        "Toshloq (Qiyichirchiq tumani)",
        "Toshqin",
        "Toyloq",
        "Toʻraqoʻrgʻon",
        "Tulga",
        "Turg'oq",
        "Turkmen",
        "Turkmen (Xatirchi tumani)",
        "Tutzor",
        "Tuyabo'g'iz",
        "Uchko'prik",
        "Uchqizil",
        "Uchqo'rg'on",
        "Uchquduq",
        "Uchquloch",
        "Uchtepa",
        "Ulug'bek",
        "Umar",
        "Unqo'rg'on",
        "Unxayat",
        "Uramas",
        "Urganch",
        "Urgut",
        "Usmat",
        "Usmon Nosir",
        "Uychi",
        "Uyrat",
        "Uzgarish",
        "Uzilishkent",
        "Uzun",
        "Vangozi",
        "Vaxshivor",
        "Vobkent",
        "Vodil",
        "Vodiy (Denov tumani)",
        "Xalkobod",
        "Xalkobod (Kegayli tumani)",
        "Xalkobod (Yangiyo'l tumani)",
        "Xanka",
        "Xaqqulobod",
        "Xarakat",
        "Xazarasp",
        "Xitoyan",
        "Xiva",
        "Xo'jaabdujabbar (Chiroqchi tumani)",
        "Xo'ja Axrori Vali",
        "Xo'jand (Yesin)",
        "Xo'jaobod",
        "Xo'jarabot",
        "Xo'jasoat",
        "Xo'jikent (Bo'stonliq tumani)",
        "Xoja Yakshabo",
        "Xonbandi",
        "Xonobod",
        "Xonobod (Namangan tumani)",
        "Xonobod (Qo'shko'pir tumani)",
        "Xonziq",
        "Xorkash",
        "Xos",
        "Xovos",
        "Xoʻja Yaqshba",
        "Xoʻjayli",
        "Xo‘jaqishloq",
        "Xo‘jaqo‘rg‘on (Toshrabot)",
        "Xusnobod",
        "Xvan Man G'im",
        "Yakkabog'",
        "Yallama",
        "Yangiarik",
        "Yangibino",
        "Yangibozor",
        "Yangibozor (Peshku tumani)",
        "Yangibozor (Yangibozor tumani)",
        "Yangi Chinoz (Chinoz tumani)",
        "Yangihayot (Kogon tumani)",
        "YangiHayot (Qiyichirchiq tumani)",
        "Yangi Hazorbog`",
        "Yangi Kuch",
        "Yangi Marg'ilon",
        "Yangi Mirishkar",
        "Yangi Nishon",
        "Yangiobod",
        "Yangiobod (Andijon tumani)",
        "Yangiobod (Angor tumani)",
        "Yangiobod (Bo'ka tumani)",
        "Yangiobod (Sardoba tumani)",
        "Yangiovul",
        "Yangiqo'rg'on",
        "Yangirabat",
        "Yangi-Tamdi",
        "Yangixayot (Oʻrtachirchiq tumani)",
        "Yangiyer",
        "Yangiyoʻl",
        "Yarkin",
        "Yaypan",
        "Yolg'izbog",
        "Yom",
        "Yorqishloq",
        "Yoshlarobod",
        "Yozyovon",
        "Yukari-Og'alik",
        "Yuqori Bachqir",
        "Yuqori-Machay",
        "Yuqori Valik",
        "Zafar",
        "Zafarobod",
        "Zafarobod (Konimex tumani)",
        "Zahlik",
        "Zangiota",
        "Zarafshon",
        "Zarbdor",
        "Zarkent",
        "Zarkent (Farg‘ona viloyati)",
        "Zarkent (Qo'shrabot tumani)",
        "Zartepa",
        "Zavrok",
        "Zhaloyir",
        "Ziyodin",
        "Ziyokor",
        "Zomin"
    ];

    const [searchUzbekistanLocations, setSearchUzbekistanLocations] = useState<string[]>([])

    useEffect(() => {
        if (!searchValue.trim()) {
            setSearchUzbekistanLocations(uzbekistanLocations)
        } else {
            setSearchUzbekistanLocations(
                uzbekistanLocations.filter(item =>
                    item.trim().toLowerCase().includes(searchValue.trim().toLowerCase())
                )
            )
        }
    }, [searchValue])
    return (
        <View style={{ width: '80%', justifyContent: 'center', maxWidth: 500, flexDirection: 'row', alignItems: 'center' }}>
            <View
                {...({
                    onStartShouldSetResponder: () => true,
                    onClick: (e: any) => e.stopPropagation(),
                    onResponderTerminationRequest: () => false,
                })}
                style={{
                    gap: 6,
                    width: '100%',
                    backgroundColor: 'white',
                    borderRadius: 20,
                    padding: 6,
                    zIndex: 99999999999999,
                    maxHeight: 600,
                    height: '82%'
                }}
            >
                <TextInput
                    onChangeText={setSearchValue}
                    value={searchValue}
                    style={{
                        fontSize: 18,
                        color: '#333',
                        outline: 'none',
                        borderWidth: 1,
                        borderColor: 'rgb(226, 245, 255)',
                        borderRadius: 14,
                        padding: 8,
                        ...Platform.select({ web: { outlineStyle: 'none' } }),
                    }}
                    placeholder={
                        lan === 'en' ? 'Search region' :
                            lan === 'ru' ? 'Искать регион' :
                                'Hududni qidirish'
                    }
                    placeholderTextColor="#1A73E8"
                />

                <ScrollView>

                    {
                        searchUzbekistanLocations.map(item => (
                            <TouchableOpacity
                                key={item}
                                onPress={() => { setLocation(item); setLocationOpen(false); }}
                                style={{
                                    paddingVertical: 12,
                                    paddingHorizontal: 6,
                                    borderRadius: 14,
                                    backgroundColor: 'rgba(226, 245, 255, 0.6)',
                                    width: '100%',
                                    alignItems: 'center',
                                    flexDirection: 'row',
                                    flex: 1,
                                    marginBottom: 4
                                }}
                            >
                                <Text style={{ textTransform: 'uppercase', fontSize: 16, color: '#1A73E8' }}>{item}</Text>
                            </TouchableOpacity>
                        ))
                    }
                </ScrollView>
            </View>
        </View>
    )
}

export default Location